/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clasificacion/cpc/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend Cpc */
        post: operations["recommend_cpc_clasificacion_cpc_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patentes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Patents */
        get: operations["list_patents_patentes__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patentes/search/semantic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Semantic
         * @description Búsqueda híbrida PostgreSQL FTS + Sentence-BERT con fusión RRF.
         *
         *     A diferencia de `GET /patentes/?q=`, este endpoint:
         *       * calcula el embedding de la query con Sentence-BERT,
         *       * llama al RPC `search_patentes_hybrid` en Supabase,
         *       * devuelve los resultados ordenados por `rrf_score`.
         */
        post: operations["search_semantic_patentes_search_semantic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patentes/{patent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patent */
        get: operations["get_patent_patentes__patent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patentes/{patent_id}/similares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Similares
         * @description Patentes más cercanas a la dada (KNN puro sobre embedding).
         */
        get: operations["get_similares_patentes__patent_id__similares_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /** History */
            history?: components["schemas"]["Message"][];
            /** Message */
            message: string;
            /** Patent Ids */
            patent_ids?: number[];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Reply */
            reply: string;
        };
        /** CpcClassificationPathItem */
        CpcClassificationPathItem: {
            /** Code */
            code: string;
            /**
             * Level
             * @enum {string}
             */
            level: "section" | "class" | "subclass" | "main_group";
            /** Title */
            title: string;
        };
        /** CpcClassificationRequest */
        CpcClassificationRequest: {
            /** Description */
            description: string;
            /**
             * Top K
             * @default 8
             */
            top_k: number;
        };
        /** CpcClassificationResponse */
        CpcClassificationResponse: {
            /** Google Patents Query */
            google_patents_query: string;
            /** Keywords */
            keywords: string[];
            /**
             * Local Fallback
             * @default false
             */
            local_fallback: boolean;
            /** Notes */
            notes: string;
            /** Recommended Codes */
            recommended_codes: components["schemas"]["RecommendedCpcCode"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Message */
        Message: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "model";
        };
        /** PaginatedResponse */
        PaginatedResponse: {
            /** Count */
            count: number;
            /** Data */
            data: components["schemas"]["PatentSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * Patent
         * @description Versión completa: incluye descripción y claims (texto largo).
         */
        Patent: {
            /** Ab */
            ab?: string | null;
            /** Apc */
            apc?: string | null;
            /** Claimen */
            claimen?: string | null;
            /** Cluster Id */
            cluster_id?: number | null;
            /** Cpc */
            cpc?: string | null;
            /** Descripcion */
            descripcion?: string | null;
            /** Espacenet */
            espacenet?: string | null;
            /** Ic */
            ic?: string | null;
            /** Id */
            id: number;
            /** Lg St */
            lg_st?: string | null;
            /** Ls */
            ls?: string | null;
            /** Pc */
            pc?: string | null;
            /** Pd */
            pd?: string | null;
            /** Pn */
            pn: string;
            /** Ti */
            ti?: string | null;
            /** Ws */
            ws?: string | null;
            /** Ww */
            ww?: string | null;
        };
        /**
         * PatentSummary
         * @description Versión ligera para listados (sin texto largo).
         */
        PatentSummary: {
            /** Ab */
            ab?: string | null;
            /** Apc */
            apc?: string | null;
            /** Cluster Id */
            cluster_id?: number | null;
            /** Cpc */
            cpc?: string | null;
            /** Espacenet */
            espacenet?: string | null;
            /** Ic */
            ic?: string | null;
            /** Id */
            id: number;
            /** Lg St */
            lg_st?: string | null;
            /** Ls */
            ls?: string | null;
            /** Pc */
            pc?: string | null;
            /** Pd */
            pd?: string | null;
            /** Pn */
            pn: string;
            /** Ti */
            ti?: string | null;
            /** Ws */
            ws?: string | null;
            /** Ww */
            ww?: string | null;
        };
        /** RecommendedCpcCode */
        RecommendedCpcCode: {
            /** Classification Path */
            classification_path?: components["schemas"]["CpcClassificationPathItem"][];
            /** Code */
            code: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /**
             * Level
             * @default subgroup
             * @enum {string}
             */
            level: "main_group" | "subgroup";
            /** Reason */
            reason: string;
            /** Retrieval Score */
            retrieval_score: number;
            /** Title */
            title: string;
        };
        /** SemanticSearchRequest */
        SemanticSearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 20
             */
            top_k: number;
        };
        /** SemanticSearchResponse */
        SemanticSearchResponse: {
            /** Count */
            count: number;
            /** Data */
            data: components["schemas"]["SemanticSearchResult"][];
            /** Query */
            query: string;
        };
        /**
         * SemanticSearchResult
         * @description Resultado del RPC `search_patentes_hybrid`.
         */
        SemanticSearchResult: {
            /** Ab */
            ab?: string | null;
            /** Apc */
            apc?: string | null;
            /** Cluster Id */
            cluster_id?: number | null;
            /** Cpc */
            cpc?: string | null;
            /** Espacenet */
            espacenet?: string | null;
            /** Fts Rank */
            fts_rank?: number | null;
            /** Ic */
            ic?: string | null;
            /** Id */
            id: number;
            /** Lg St */
            lg_st?: string | null;
            /** Ls */
            ls?: string | null;
            /** Pc */
            pc?: string | null;
            /** Pd */
            pd?: string | null;
            /** Pn */
            pn: string;
            /** Rrf Score */
            rrf_score?: number | null;
            /** Sem Rank */
            sem_rank?: number | null;
            /** Ti */
            ti?: string | null;
            /** Ws */
            ws?: string | null;
            /** Ww */
            ww?: string | null;
        };
        /** SimilarPatent */
        SimilarPatent: {
            /** Ab */
            ab?: string | null;
            /** Apc */
            apc?: string | null;
            /** Cluster Id */
            cluster_id?: number | null;
            /** Distance */
            distance?: number | null;
            /** Id */
            id: number;
            /** Pn */
            pn?: string | null;
            /** Ti */
            ti?: string | null;
            /** Ww */
            ww?: string | null;
        };
        /** SimilarPatentsResponse */
        SimilarPatentsResponse: {
            /** Count */
            count: number;
            /** Data */
            data: components["schemas"]["SimilarPatent"][];
            /** Patent Id */
            patent_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    chat_chat__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_cpc_clasificacion_cpc_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CpcClassificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CpcClassificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patents_patentes__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_semantic_patentes_search_semantic_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patent_patentes__patent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_similares_patentes__patent_id__similares_get: {
        parameters: {
            query?: {
                top_k?: number;
            };
            header?: never;
            path: {
                patent_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarPatentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
